# fly.toml app configuration file generated for esports-api on 2025-04-30T19:19:16-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'esports-api'
primary_region = 'atl'
kill_signal = 'SIGINT'
kill_timeout = '5s'

[deploy]
  strategy = 'rolling'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
